# Generated by Django 4.0.4 on 2022-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
