# Generated by Django 4.0.4 on 2022-04-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
