# Generated by Django 4.0.4 on 2022-04-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.table'),
        ),
    ]
