# Generated by Django 4.0.4 on 2022-05-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_order_reminder'),
        ('crm', '0004_alter_lead_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='LeadComment',
        ),
    ]
