# Generated by Django 4.0.4 on 2022-05-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_comment_leadcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadcomment',
            options={'ordering': ('pin',)},
        ),
    ]
