# Generated by Django 4.0.4 on 2022-05-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_leadcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadcomment',
            options={'ordering': ('-pin',)},
        ),
    ]
