# Generated by Django 4.0.4 on 2022-05-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_lead_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='droped_table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
