# Generated by Django 4.0.3 on 2022-04-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_order_date_process_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
