# Generated by Django 4.0.3 on 2022-04-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_course_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account',
        ),
        migrations.AddField(
            model_name='order',
            name='fio',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
