# Generated by Django 4.0.3 on 2022-04-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_remove_order_account_order_fio_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercomment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='ordercomment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderComment',
        ),
    ]
