# Generated by Django 4.0.4 on 2022-04-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_order_ordercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_process_9',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
