# Generated by Django 4.0.4 on 2022-04-22 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_order_date_process_9'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercomment',
            options={'ordering': ('-date_create',)},
        ),
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.account'),
        ),
    ]
