# Generated by Django 4.0.4 on 2022-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_alter_ordercomment_options_order_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reminder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
